# Generated by Django 6.0.6 on 2026-06-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
